import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Test Survey",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-blue-600 text-white p-4 fixed w-full top-0 z-50">
          <div className="container mx-auto flex justify-between items-center">
            <h1 className="text-xl font-bold text-white"><a href="/">Test-Survey</a></h1>
            <ul className="flex space-x-8">
              <li>
                <a href="/" className="hover:text-white/80">Home</a>
              </li>
              <li>
                <a href="/survey" className="hover:text-white/80">설문조사</a>
              </li>
              <li>
                <a href="/survey2" className="hover:text-white/80">설문조사2</a>
              </li>
              <li>
                <a href="/survey/settings" className="hover:text-white/80">설문조사 설정 (old)</a>
              </li>
              <li>
                <a href="/survey/settings/new-style" className="hover:text-white/80">설문조사 설정 (new)</a>
              </li>
              <li>
                <a href="/survey/settings/new-style-with-modal" className="hover:text-white/80">설문조사 설정 (new with modal)</a>
              </li>
            </ul>
          </div>
        </nav>
        <main className="container mx-auto p-8 flex-1 pt-16">
          {children}
        </main>
      </body>
    </html>
  );
}
